# Generated by Django 5.1 on 2024-09-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_buku_cover_buku_tanggal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='tanggal',
        ),
    ]
